version: "3"

services:
  url-shorten:
    image: bh3139/shorturl:0.2
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    depends_on:
      - db


  db:
    image: redis
    ports:
      - 127.0.0.1:6543:6543
    restart: always
    volumes:
      - redis-storage:/var/lib/redis

volumes:
  redis-storage:
